fix(lambda): bump @middy/core from 3.6.2 to 4.7.0 in /lambdas (#3609)
Bumps
[@middy/core](https://github.com/middyjs/middy/tree/HEAD/packages/core)
from 3.6.2 to 4.7.0.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/middyjs/middy/releases"><code>@​middy/core</code>'s
releases</a>.</em></p>
<blockquote>
<h2>4.7.0</h2>
<h2>What's Changed</h2>
<ul>
<li>Add ability to set default headers in
<code>http-header-normalizer</code> / http-json-body-parser - json as
default content type <a
href="https://github.com/middyjs/middy/tree/HEAD/packages/core/issues/1120">#1120</a>
<a href="https://github.com/qoomon"><code>@​qoomon</code></a></li>
</ul>
<p><strong>Full Changelog</strong>: <a
href="https://github.com/middyjs/middy/compare/4.6.6...4.7.0">https://github.com/middyjs/middy/compare/4.6.6...4.7.0</a></p>
<h2>4.6.6</h2>
<h2>What's Changed</h2>
<ul>
<li>Fix typo by <a
href="https://github.com/michael-k"><code>@​michael-k</code></a> in <a
href="https://redirect.github.com/middyjs/middy/pull/1110">middyjs/middy#1110</a></li>
<li>docs: add Powertools idempotency + fix typo by <a
href="https://github.com/dreamorosi"><code>@​dreamorosi</code></a> in <a
href="https://redirect.github.com/middyjs/middy/pull/1115">middyjs/middy#1115</a></li>
<li>TypeError: Cannot read properties of undefined (reading 'Accept') <a
href="https://github.com/phawxby"><code>@​phawxby</code></a> <a
href="https://github.com/middyjs/middy/tree/HEAD/packages/core/issues/1121">#1121</a></li>
</ul>
<h2>New Contributors</h2>
<ul>
<li><a href="https://github.com/michael-k"><code>@​michael-k</code></a>
made their first contribution in <a
href="https://redirect.github.com/middyjs/middy/pull/1110">middyjs/middy#1110</a></li>
</ul>
<p><strong>Full Changelog</strong>: <a
href="https://github.com/middyjs/middy/compare/4.6.5...4.6.6">https://github.com/middyjs/middy/compare/4.6.5...4.6.6</a></p>
<h2>4.6.5</h2>
<h2>What's Changed</h2>
<ul>
<li>SSM: fix: some mixes of named/paths results in undefined named param
values by <a
href="https://github.com/WillGresham"><code>@​WillGresham</code></a> in
<a
href="https://redirect.github.com/middyjs/middy/pull/1108">middyjs/middy#1108</a></li>
<li>fix: validator benchmark by <a
href="https://github.com/aztalbot"><code>@​aztalbot</code></a> in <a
href="https://redirect.github.com/middyjs/middy/pull/1105">middyjs/middy#1105</a></li>
</ul>
<h2>New Contributors</h2>
<ul>
<li><a
href="https://github.com/WillGresham"><code>@​WillGresham</code></a>
made their first contribution in <a
href="https://redirect.github.com/middyjs/middy/pull/1108">middyjs/middy#1108</a></li>
</ul>
<p><strong>Full Changelog</strong>: <a
href="https://github.com/middyjs/middy/compare/4.6.4...4.6.5">https://github.com/middyjs/middy/compare/4.6.4...4.6.5</a></p>
<h2>4.6.4</h2>
<h2>What's Changed</h2>
<ul>
<li>fix(core): allow sync handlers by <a
href="https://github.com/cjbt"><code>@​cjbt</code></a> in <a
href="https://redirect.github.com/middyjs/middy/pull/1102">middyjs/middy#1102</a></li>
</ul>
<p><strong>Full Changelog</strong>: <a
href="https://github.com/middyjs/middy/compare/4.6.3...4.6.4">https://github.com/middyjs/middy/compare/4.6.3...4.6.4</a></p>
<h2>4.6.3</h2>
<h2>What's Changed</h2>
<ul>
<li>Fixed s3 headers[headerName].trim is not a function <a
href="https://github.com/middyjs/middy/tree/HEAD/packages/core/issues/1097">#1097</a>
<a
href="https://github.com/carrickkv2"><code>@​carrickkv2</code></a></li>
</ul>
<p><strong>Full Changelog</strong>: <a
href="https://github.com/middyjs/middy/compare/4.6.2...4.6.3">https://github.com/middyjs/middy/compare/4.6.2...4.6.3</a></p>
<h2>4.6.2</h2>
<h2>What's Changed</h2>
<ul>
<li><code>http-*-pody-parser</code> now throws proper error when no
headers are passed in.</li>
</ul>
<p><strong>Full Changelog</strong>: <a
href="https://github.com/middyjs/middy/compare/4.6.1...4.6.2">https://github.com/middyjs/middy/compare/4.6.1...4.6.2</a></p>
<h2>4.6.1</h2>
<h2>What's Changed</h2>
<ul>
<li>chore: fix website search by <a
href="https://github.com/lmammino"><code>@​lmammino</code></a> in <a
href="https://redirect.github.com/middyjs/middy/pull/1091">middyjs/middy#1091</a></li>
<li>fix: Update http-content-encoding.md by <a
href="https://github.com/cjbt"><code>@​cjbt</code></a> in <a
href="https://redirect.github.com/middyjs/middy/pull/1094">middyjs/middy#1094</a></li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/middyjs/middy/commit/f085b85b2c8f18a97fdf8a7062e770b444185dd8"><code>f085b85</code></a>
chore: version bump</li>
<li><a
href="https://github.com/middyjs/middy/commit/9784bfe6b02db56b3893e2117de33804358a3932"><code>9784bfe</code></a>
chore: version bump</li>
<li><a
href="https://github.com/middyjs/middy/commit/b1e3d4af5ac55bea06bb6e78ca4784de6c4aae87"><code>b1e3d4a</code></a>
chore: dep update</li>
<li><a
href="https://github.com/middyjs/middy/commit/573d7b0bb243d8c5a9bcb00cf29d031aa7a0c606"><code>573d7b0</code></a>
chore: version bump</li>
<li><a
href="https://github.com/middyjs/middy/commit/706ec39ce569407d51007200b995542ad3d7af2b"><code>706ec39</code></a>
chore: version bump</li>
<li><a
href="https://github.com/middyjs/middy/commit/3fd50b88a28c41fdc64022532a068d821b3c78df"><code>3fd50b8</code></a>
Merge pull request <a
href="https://github.com/middyjs/middy/tree/HEAD/packages/core/issues/1102">#1102</a>
from cjbt/issue-1096-accept-sync-handlers</li>
<li><a
href="https://github.com/middyjs/middy/commit/4873f6e64cc4a7dbe8739ed3e45ef458dfe0dba1"><code>4873f6e</code></a>
chore: version bump</li>
<li><a
href="https://github.com/middyjs/middy/commit/67eced10ab69334b185b36c39db1f00900884710"><code>67eced1</code></a>
chore: dep update</li>
<li><a
href="https://github.com/middyjs/middy/commit/28f2e1ded0eae7a619d42af0b0e2e75475505690"><code>28f2e1d</code></a>
fix(core): added excplicit typing</li>
<li><a
href="https://github.com/middyjs/middy/commit/e80e9c2c878edf302e9315661da4d8977effded9"><code>e80e9c2</code></a>
fix(core): fix lint issues</li>
<li>Additional commits viewable in <a
href="https://github.com/middyjs/middy/commits/4.7.0/packages/core">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=@middy/core&package-manager=npm_and_yarn&previous-version=3.6.2&new-version=4.7.0)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore <dependency name> major version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's major version (unless you unignore this specific
dependency's major version or upgrade to it yourself)
- `@dependabot ignore <dependency name> minor version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's minor version (unless you unignore this specific
dependency's minor version or upgrade to it yourself)
- `@dependabot ignore <dependency name>` will close this group update PR
and stop Dependabot creating any more for the specific dependency
(unless you unignore this specific dependency or upgrade to it yourself)
- `@dependabot unignore <dependency name>` will remove all of the ignore
conditions of the specified dependency
- `@dependabot unignore <dependency name> <ignore condition>` will
remove the ignore condition of the specified dependency and ignore
conditions


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>